plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    def loader = "fabric"

    def veil = "foundry.veil:veil-${loader}-${minecraft_version}:${veil_version}"
    modImplementation(veil) {
        exclude group: 'maven.modrinth'
        exclude group: 'me.fallenbreath'
    }

    def flywheelApi = "dev.engine-room.flywheel:flywheel-${loader}-api-${minecraft_version}:${flywheel_version}"
    modCompileOnly(flywheelApi)

    def flywheel = "dev.engine-room.flywheel:flywheel-${loader}-${minecraft_version}:${flywheel_version}"
    modImplementation(flywheel)

    def sable = "dev.ryanhcode.sable:sable-${loader}-${minecraft_version}:${sable_version}"
    modImplementation(sable) {
        exclude group: 'foundry.veil'
    }

//    def sableCompanion = "dev.ryanhcode.sable-companion:sable-companion-common-${minecraft_version}:${sable_companion_version}"
//    api(sableCompanion)
}


fabricApi {
    configureDataGeneration() {
        outputDirectory = file('../common/src/generated/resources/')
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
