plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/generated/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'

    def loader = "neoforge"

    def veil = "foundry.veil:veil-${loader}-${minecraft_version}:${veil_version}"
    implementation(veil) {
        exclude group: 'maven.modrinth'
        exclude group: 'me.fallenbreath'
    }

    def flywheelApi = "dev.engine-room.flywheel:flywheel-${loader}-api-${minecraft_version}:${flywheel_version}"
    compileOnly(flywheelApi)

    def flywheel = "dev.engine-room.flywheel:flywheel-${loader}-${minecraft_version}:${flywheel_version}"
    implementation(flywheel)

    def sable = "dev.ryanhcode.sable:sable-${project.name}-${minecraft_version}:${sable_version}"
    implementation(sable) {
        exclude group: 'foundry.veil'
    }

//    def sableCompanion = "dev.ryanhcode.sable-companion:sable-companion-common-${minecraft_version}:${sable_companion_version}"
//    api(sableCompanion)
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

dependencies {
}

